language: ruby
rvm:
  - 2.5.5
  - 2.0.0
  - 1.9.3
  - jruby-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails3_1
  - gemfiles/Gemfile.rails4_0
before_script:
  - mysql -e 'create database strano_test'
  - psql -c 'create database strano_test' -U postgres
  - RAILS_ENV=test bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare
